name: Pull Request Approval Info

on:
  pull_request_review:
    types:
      - submitted

jobs:
  get-approval-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR info
        id: pr-info
        run: echo "::set-output name=pr-number::${{ github.event.pull_request.number }}"

      - name: Get GitHub Pull Request Reviewers
        id: reviews
        uses: LiamPerson/get-reviews-action@v1.0
        with:
          RELEASES_JSON_FILE: ${{ steps.pr-info.outputs.pr-number }}-reviews.json

      - name: Print Reviewers
        run: cat ${{ steps.reviews.outputs.reviews_file_path }}
